# Generated by Django 4.2.3 on 2023-07-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_songs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songs",
            name="song",
            field=models.FileField(blank=True, null=True, upload_to="audio/songs/"),
        ),
    ]
